apiVersion: v1
kind: Service
metadata:
  name: ai-study-buddy-service
  namespace: argocd
spec:
  selector:
    app: ai-study-buddy
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000